### ISSUE TITLE
Adopt some version tagging?

### ISSUE THREAD

**Issue by luckymike** [terraform-community-modules/tf_aws_vpc#14]
Hey there!

First off, thank you for maintaining a vpc module. It's super handy!

Second, I'm hoping you'd consider adopting some version tagging for this repo. I'm using it in a few places, and was bit yesterday by the update to support 0.7.0, because we're still using 0.6.16. I was able to ping back to the commit before 0.7.0 support using the SHA, but I think that having a tagged version number would make that friendlier, and also might communicate more clearly to users that they might want to use a specific version to ensure that future updates don't cause any surprises.

Thanks!

**Comment by antonbabenko** [comment]
Thanks for feedback. 0.7 is the first big release when there is a real use-case for versioning.

I suggest that we tag modules which are not compatible with 0.7, so people can stick to specific version, but have `master` branch always up-to-date with latest stable version of Terraform.

There are few other `terraform-community-modules` where we already use semantic versioning to some degree.

**Comment by antonbabenko** [comment]
Added note about versioning to readme - https://github.com/terraform-community-modules/tf_aws_vpc/commit/796e22481bffa1955c36a28694b6508455ef77be
