### ISSUE TITLE
Private DNS versus AWS Hosted DNS

### ISSUE THREAD

**Issue by rhiann0n** [terraform-community-modules/tf_aws_vpc#24]
Thanks for the documentation, but please understand the verbiage in description is wrong.

https://github.com/terraform-community-modules/tf_aws_vpc/pull/23

As an engineer, the term 'private DNS' does not equate to Amazon DNS, which would not be private, but hosted in a private network silo, known as a VPC.

Using the settings as directed indicates things are setup backwards according to the description.
'should be true if you want to use private DNS within the VPC'

Private DNS refers to Non-Amazon DNS in most definitions.
Setting the definition to true as it currently stands indicates one is to use Amazon DNS, and will be suprised when they can ping 8.8.8.8 and nothing else as the VPC expects private dns servers in place.

Does this make sense?

**Comment by antonbabenko** [comment]
As this module is about AWS specific resources within VPC we are referring to private DNS as defined in AWS documentation and I don't see the way we can change it without misleading the majority of existing users. Closing for now.
