### ISSUE TITLE
Module not working anymore due to trying to tag resources does not support tag

### ISSUE THREAD

**Issue by thiagonache** [terraform-community-modules/tf_aws_vpc#29]
Hi there,

I think this commit https://github.com/terraform-community-modules/tf_aws_vpc/commit/56bf2681e218ed6a18ddc95a8408d8529376d654 broke module
       
       Errors:
       
         * aws_eip.nateip #2: : invalid or unknown key: tags
         * aws_eip.nateip #0: : invalid or unknown key: tags
         * aws_eip.nateip #1: : invalid or unknown key: tags
         * aws_nat_gateway.natgw #0: : invalid or unknown key: tags
         * aws_nat_gateway.natgw #2: : invalid or unknown key: tags
         * aws_nat_gateway.natgw #1: : invalid or unknown key: tags
         * aws_route.private_nat_gateway #1: : invalid or unknown key: tags
         * aws_route.private_nat_gateway #2: : invalid or unknown key: tags
         * aws_route.private_nat_gateway #0: : invalid or unknown key: tags

All these resources do not have tags.

**Comment by thiagonache** [comment]
https://github.com/terraform-community-modules/tf_aws_vpc/pull/30

**Comment by antonbabenko** [comment]
You are absolutely right! I am sorry that this was merged without proper checking. I have checked syntax of single line, but didn't check fully on all resources.
