### ISSUE TITLE
Support aws_availability_zones

### ISSUE THREAD

**Issue by analytically** [terraform-community-modules/tf_aws_vpc#37]
See https://github.com/hashicorp/terraform/pull/11482

```
data "aws_availability_zones" "available" {}

resource "aws_subnet" "public" {
  count = "${length(data.aws_availability_zones.available.id)}"
  availability_zone = "${data.aws_availability_zones.available.id[count.index]}"
}
```

**Comment by nyambati** [comment]
@analytically I think you can still use the module as is with `aws_availability_zones`.  This module requires a list of `azs` to create subnets. You can supply that list to the module, here is an example.
```hcl 
module "vpc" {
...
  azs                = ["${data.aws_availability_zones.available.names}"]
...
}
```
I think the current setup makes the module more flexible providing more control on how many subnets you would like to create.

**Comment by analytically** [comment]
Thanks!
