### ISSUE TITLE
enabling Flow Logs

### ISSUE THREAD

**Issue by afeld** [terraform-community-modules/tf_aws_vpc#64]
Having flow logs enabled is useful for troubleshooting connection issues in the VPC. Thoughts about making it configurable as part of the module? Happy to submit a pull request with a variation of [the Terraform example](https://www.terraform.io/docs/providers/aws/r/flow_log.html), if there's interest. Thanks!

**Comment by antonbabenko** [comment]
Absolutely! You are welcome to submit a PR.

**Comment by afeld** [comment]
Hmm, there doesn't seem to be a good way to make it conditional, and I assume it's not desirable to include it for everyone, right?

**Comment by afeld** [comment]
Anyway, created a module for it:

https://github.com/GSA/terraform-vpc-flow-log

More than happy to transfer to @terraform-aws-modules if there's interest.

**Comment by antonbabenko** [comment]
Good work with VPC flow log and I agree that it would be a great addition to https://github.com/terraform-aws-modules/terraform-aws-vpc.

VPC flow log is a single VPC resource with several parameters. It can be merged into VPC module rather easily.

I have made an issue with some details provided - https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/23. Please tell me there if you have questions.
